<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="2" total="4" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-27T18:45:51 IST" name="Suite" finished-at="2024-09-27T18:45:59 IST" duration-ms="8753">
    <groups>
      <group name="Error Handling">
        <method signature="ErrorValidationTest.loginErrorValidation()[pri:0, instance:MyEcommerce.Ecommerce.tests.ErrorValidationTest@515c6049]" name="loginErrorValidation" class="MyEcommerce.Ecommerce.tests.ErrorValidationTest"/>
      </group> <!-- Error Handling -->
    </groups>
    <test started-at="2024-09-27T18:45:51 IST" name="SubmitCartTest" finished-at="2024-09-27T18:45:51 IST" duration-ms="11">
    </test> <!-- SubmitCartTest -->
    <test started-at="2024-09-27T18:45:51 IST" name="ErrorValidationTest" finished-at="2024-09-27T18:45:59 IST" duration-ms="8753">
      <class name="MyEcommerce.Ecommerce.tests.ErrorValidationTest">
        <test-method is-config="true" signature="startApplication()[pri:0, instance:MyEcommerce.Ecommerce.tests.ErrorValidationTest@515c6049]" started-at="2024-09-27T18:45:51 IST" name="startApplication" finished-at="2024-09-27T18:45:56 IST" duration-ms="5090" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:MyEcommerce.Ecommerce.tests.ErrorValidationTest@515c6049]" started-at="2024-09-27T18:45:56 IST" name="loginErrorValidation" finished-at="2024-09-27T18:45:56 IST" duration-ms="518" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at MyEcommerce.Ecommerce.tests.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="startApplication()[pri:0, instance:MyEcommerce.Ecommerce.tests.ErrorValidationTest@515c6049]" started-at="2024-09-27T18:45:56 IST" name="startApplication" finished-at="2024-09-27T18:45:59 IST" duration-ms="2322" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:MyEcommerce.Ecommerce.tests.ErrorValidationTest@515c6049]" started-at="2024-09-27T18:45:59 IST" name="loginErrorValidation" finished-at="2024-09-27T18:45:59 IST" duration-ms="763" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
      </class> <!-- MyEcommerce.Ecommerce.tests.ErrorValidationTest -->
    </test> <!-- ErrorValidationTest -->
  </suite> <!-- Suite -->
</testng-results>
